### ISSUE TITLE
Selective Mob Griefing

### ISSUE THREAD

**Issue by Electravess** [MSCraftWiki/mscraft.org#1]
Some mob farms (e.g. Drowned Farms) only work with mob griefing enabled. Of course, having mob griefing enabled isn't the best. 

Disabling mob griefing causes the following:

- disable Creeper, Ghast, and Wither explosions
- disable Ender Dragon block damage
- remove the ability for Endermen to pick up blocks
- remove the ability for Zombies to break doors
- make crops unharvestable by Villagers and Rabbits (breaks Villager breeding)
- remove the ability for Snow Golems to create snow.
- remove the ability for Sheep to eat grass (and consequently, be unable to regrow wool)
- remove the ability for mobs to pick up items.

There are datapacks which allow for disabling only certain creature's griefing:

https://vanillatweaks.net/picker/datapacks/
(There are also many other basic "tweaks" available here if you so choose to add any of them)

There are 3 datapacks here- one to stop **Creeper** explosions damaging blocks, another to stop **Ghast** explosions damaging blocks, and a third for stopping **Endermen** picking up blocks.

There are some problems though - the Ender Dragon would still destroy things, as would the Wither. While Wither destruction is useful in farms e.g. tree farms, they also have massive griefing potential, so I'd leave it up to the owner to decide whether it would be a good idea to let the Wither damage stuff.

An alternative solution is apparently able to be done using a plugin called EssentialsX, which one can use to freely modify the properties of individual mobs to stop them from griefing. I have absolutely no clue how this is done in practice though.

Thanks for considering this!

**Comment by bushtail** [comment]
CLOSED - the community has decided to set mobGriefing to false and remove the datapacks. Sorry for any inconvenience this causes!
